# default profile
spring:
  profiles:
    active: dev
---
# dev (replace this with testcontainers!)
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/testx
    username: johnshift
    password: John123!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
---
# production
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: johnshift
    password: John123!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
