# default profile
spring:
  profiles:
    active: dev
---
# dev (replace this with testcontainers!)
spring:
  config.activate.on-profile: dev
  sql.init.mode: always
  datasource:
    url: jdbc:tc:mysql://localhost:3306/testx
    username: johnshift
    password: John123!
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # ddl-auto: create
      ddl-auto: none
  # flyway:
  #   locations: classpath:db/migration
---
# production
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: johnshift
    password: John123!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
