# dev (mirror production env locally)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: johnshift
    password: John123!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
