name: CI/CD Pipeline
on: [push]
jobs:
  # 3 jobs just to demonstrate staging pipelines
  build:
    name: Build Source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run unit-tests
        run: mvn clean compile
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run unit-tests
        run: mvn clean test
  integtation-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run integration-tests
        run: mvn clean verify
      - name: Coverage
        uses: cicirello/jacoco-badge-generator@v2.4.1