name: CI/CD Pipeline
on: [push]
jobs:
  # 3 jobs just to demonstrate staging pipelines
  build:
    name: Build Source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run unit-tests
        run: mvn clean compile
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run unit-tests
        run: mvn clean test
  integtation-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run integration-tests
        run: mvn clean verify

      - name: Generate coverage badge
        uses: cicirello/jacoco-badge-generator@v2.4.1
        with:
          generate-coverage-badge: 
          
      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'YOUR NAME HERE'
            git config --global user.email 'YOUR-GITHUB-USERID@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/