name: CI/CD
on: 
  push:
  workflow_dispatch:

jobs:
  integtation-test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run integration-tests
        run: mvn clean verify

      - name: Jacoco report
        run: mvn -DskipTests install jacoco:report

      - name: Generate coverage badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.4.1
        with:
          generate-coverage-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"
          
      - name: Commit and push
        run: |
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'John Ballesters'
            git config --global user.email 'johnshift@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/